version: '3.8'

services:
  app:
    build: .
    ports:
      - '10000:10000'
    environment:
      - NODE_ENV=production
      - PORT=10000
      - MONGODB_URI=mongodb+srv://lukametr:akukelaAIO12@cluster0.l56lnkq.mongodb.net/saba?retryWrites=true&w=majority&appName=Cluster0
      - JWT_SECRET=saba-secure-jwt-key-2024-06-12
      - NEXT_PUBLIC_API_URL=https://sabapp.com/api
    depends_on:
      - mongo
    volumes:
      - ./uploads:/app/uploads

  mongo:
    image: mongo:7
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=sabap

volumes:
  mongo_data:
