version: '3.8'

services:
  app:
    build: .
    ports:
      - "10000:10000"
    environment:
      - NODE_ENV=production
      - PORT=10000
      - MONGODB_URI=mongodb://mongo:27017/sabap
      - JWT_SECRET=your-secret-key
    depends_on:
      - mongo
    volumes:
      - ./uploads:/app/uploads

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=sabap

volumes:
  mongo_data: 