services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - MONGODB_URI=mongodb://mongo:27017/saba
      - JWT_SECRET=saba-secure-jwt-key-2024-06-12
      - NEXT_PUBLIC_API_URL=http://localhost:3001/api
      - NEXT_PUBLIC_GOOGLE_CLIENT_ID=675742559993-5quocp5mgvmog0fd2g8ue03vpleb23t5.apps.googleusercontent.com
    depends_on:
      - mongo
    volumes:
      - ./uploads:/app/uploads
      - ./apps/backend/uploads:/app/apps/backend/uploads
    networks:
      - saba-network

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=saba
    networks:
      - saba-network

networks:
  saba-network:
    driver: bridge

volumes:
  mongo_data: