[build]
builder = "dockerfile"
dockerfile = "Dockerfile"

[build.buildArgs]
NEXT_PUBLIC_GOOGLE_CLIENT_ID = "${{ NEXT_PUBLIC_GOOGLE_CLIENT_ID }}"
NEXT_PUBLIC_API_URL = "https://sabapp.com/api"

[deploy]
startCommand = "node dist/main.js"
healthcheckPath = "/health"
healthcheckTimeout = 60
restartPolicyType = "always"
restartPolicyMaxRetries = 10

[environments.production]
[environments.production.variables]
NODE_ENV = "production"
MONGODB_URI = "${{ MONGODB_URI }}"
JWT_SECRET = "${{ JWT_SECRET }}"
JWT_EXPIRES_IN = "7d"
GOOGLE_CLIENT_SECRET = "${{ GOOGLE_CLIENT_SECRET }}"
GOOGLE_CLIENT_ID = "${{ NEXT_PUBLIC_GOOGLE_CLIENT_ID }}"
NEXT_PUBLIC_API_URL = "https://sabapp.com/api"
NEXT_PUBLIC_GOOGLE_CLIENT_ID = "${{ NEXT_PUBLIC_GOOGLE_CLIENT_ID }}"
CORS_ORIGIN = "https://sabapp.com,https://www.sabapp.com"