[build]
builder = "dockerfile"
dockerfile = "Dockerfile"

[deploy]
startCommand = "node dist/main.js"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "always"
restartPolicyMaxRetries = 10

[environments.production]
[environments.production.variables]
NODE_ENV = "production"
PORT = "3001"
# Using direct connection without DNS SRV
MONGODB_URI = "mongodb://lukametr:akukelaAIO12@ac-wbztgnk-shard-00-00.l56lnkq.mongodb.net:27017,ac-wbztgnk-shard-00-01.l56lnkq.mongodb.net:27017,ac-wbztgnk-shard-00-02.l56lnkq.mongodb.net:27017/saba?ssl=true&authSource=admin"
JWT_SECRET = "${{ JWT_SECRET }}"
NEXT_PUBLIC_API_URL = "https://${{ RAILWAY_PUBLIC_DOMAIN }}/api"
NEXT_PUBLIC_GOOGLE_CLIENT_ID = "${{ NEXT_PUBLIC_GOOGLE_CLIENT_ID }}"
CORS_ORIGIN = "https://${{ RAILWAY_PUBLIC_DOMAIN }}"