[build]
builder = "dockerfile"
dockerfile = "Dockerfile"

[deploy]
startCommand = "node dist/main.js"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "always"
restartPolicyMaxRetries = 10

[environments.production]
[environments.production.variables]
NODE_ENV = "production"
PORT = "3001"
# Use direct connection instead of DNS SRV
MONGODB_URI = "mongodb://lukametr:akukelaAIO12@cluster0.l56lnkq.mongodb.net:27017/saba?retryWrites=true&w=majority&appName=Cluster0"
JWT_SECRET = "${{ JWT_SECRET }}"
NEXT_PUBLIC_API_URL = "https://${{ RAILWAY_PUBLIC_DOMAIN }}/api"
NEXT_PUBLIC_GOOGLE_CLIENT_ID = "${{ NEXT_PUBLIC_GOOGLE_CLIENT_ID }}"
CORS_ORIGIN = "https://${{ RAILWAY_PUBLIC_DOMAIN }}"