[build]
builder = "dockerfile"
dockerfile = "Dockerfile"

[build.buildArgs]
NEXT_PUBLIC_GOOGLE_CLIENT_ID = "${{ NEXT_PUBLIC_GOOGLE_CLIENT_ID }}"
NEXT_PUBLIC_API_URL = "https://sabapp.com/api"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "always"
restartPolicyMaxRetries = 10

[environments.production]
[environments.production.variables]
NODE_ENV = "production"
MONGODB_URI = "mongodb+srv://lukametr:akukelaAIO12@cluster0.l56lnkq.mongodb.net/saba?retryWrites=true&w=majority"
JWT_SECRET = "super-secret-jwt-key-for-production-saba-app-123456789"
JWT_EXPIRES_IN = "7d"
GOOGLE_CLIENT_SECRET = "GOCSPX-placeholder-secret-key"
GOOGLE_CLIENT_ID = "${{ NEXT_PUBLIC_GOOGLE_CLIENT_ID }}"
NEXT_PUBLIC_API_URL = "https://sabapp.com/api"
NEXT_PUBLIC_GOOGLE_CLIENT_ID = "${{ NEXT_PUBLIC_GOOGLE_CLIENT_ID }}"
CORS_ORIGIN = "https://sabapp.com"
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/usr/bin/google-chrome-stable"
CHROME_BIN = "/usr/bin/google-chrome-stable"
BACKEND_URL = "https://sabapp.com"
NEXT_PUBLIC_BACKEND_URL = "https://sabapp.com"
NEXTAUTH_URL = "https://sabapp.com"
# Set this in Railway UI for security; placeholder here
NEXTAUTH_SECRET = "change-me-in-railway"