[build]
builder = "dockerfile"
dockerfile = "Dockerfile"

[deploy]
startCommand = "pnpm start:prod"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "always"
restartPolicyMaxRetries = 10

[environments.production]
[environments.production.variables]
NODE_ENV = "production"
PORT = "3001"
MONGODB_URI = "${{ MONGODB_URI }}"
JWT_SECRET = "${{ JWT_SECRET }}"
NEXT_PUBLIC_API_URL = "${{ RAILWAY_PUBLIC_DOMAIN }}/api"
NEXT_PUBLIC_GOOGLE_CLIENT_ID = "${{ NEXT_PUBLIC_GOOGLE_CLIENT_ID }}" 