[build]
builder = "dockerfile"
dockerfile = "Dockerfile"

[build.buildArgs]
NEXT_PUBLIC_GOOGLE_CLIENT_ID = "${{ NEXT_PUBLIC_GOOGLE_CLIENT_ID }}"
NEXT_PUBLIC_API_URL = "https://${{ RAILWAY_PUBLIC_DOMAIN }}/api"

[deploy]
startCommand = "node dist/main.js"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "always"
restartPolicyMaxRetries = 10

[environments.production]
[environments.production.variables]
NODE_ENV = "production"
PORT = "3001"
MONGODB_URI = "mongodb+srv://lukametr:akukelaAIO12@cluster0.l56lnkq.mongodb.net/saba?"
JWT_SECRET = "${{ JWT_SECRET }}"
GOOGLE_CLIENT_ID = "${{ NEXT_PUBLIC_GOOGLE_CLIENT_ID }}"
NEXT_PUBLIC_API_URL = "https://${{ RAILWAY_PUBLIC_DOMAIN }}/api"
NEXT_PUBLIC_GOOGLE_CLIENT_ID = "${{ NEXT_PUBLIC_GOOGLE_CLIENT_ID }}"
CORS_ORIGIN = "https://${{ RAILWAY_PUBLIC_DOMAIN }}"