services:
  # ბექენდის სერვისი
  - type: web
    name: saba-api
    env: node
    region: oregon
    plan: free
    buildCommand: cd apps/backend && pnpm install && pnpm build
    startCommand: cd apps/backend && pnpm start
    envVars:
      - key: PORT
        value: 3003
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
    healthCheckPath: /api/health
    autoDeploy: true

  # ფრონტენდის სერვისი
  - type: web
    name: saba-frontend
    env: node
    buildCommand: |
      npm install -g pnpm
      pnpm install
      cd apps/frontend && pnpm build
    startCommand: cd apps/frontend && pnpm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: https://saba-api-njd9.onrender.com
    healthCheckPath: /
    autoDeploy: true 