# This file is for Render.com deployment. If you are deploying to Railway, you can safely delete or ignore this file.
# To avoid confusion, you may want to remove this file from your repository if you are not using Render.

services:
  # მთავარი სერვისი - ბექენდი + ფრონტენდი ერთად
  - type: web
    name: saba-app
    env: node
    rootDir: .
    buildCommand: pnpm install && pnpm run build:render
    startCommand: pnpm run start:prod
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        sync: false
      - key: CORS_ORIGIN
        value: https://saba-app.onrender.com
      - key: NEXT_PUBLIC_API_URL
        value: https://saba-app.onrender.com
    healthCheckPath: /health
    healthCheckTimeout: 180
    autoDeploy: true
