services:
  # ბექენდი
  - type: web
    name: saba-backend
    env: node
    rootDir: apps/backend
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        sync: false
      - key: CORS_ORIGIN
        value: https://saba-frontend.onrender.com
    healthCheckPath: /api/health
    autoDeploy: true

  # ფრონტენდი
  - type: web
    name: saba-frontend
    env: node
    rootDir: apps/frontend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://saba-backend.onrender.com/api
      - key: PORT
        value: 3000
    autoDeploy: true 