services:
  # მთავარი სერვისი - ფრონტენდი და ბექენდი ერთად
  - type: web
    name: saba-app
    env: node
    rootDir: .
    buildCommand: pnpm run build:render
    startCommand: pnpm run start:prod
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: NEXT_PUBLIC_API_URL
        value: https://saba-app.onrender.com
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        value: https://saba-app.onrender.com
      - key: CORS_ORIGIN
        value: https://saba-app.onrender.com
    healthCheckPath: /api/health
    autoDeploy: true 