services:
  # ბექენდის სერვისი
  - type: web
    name: saba-api
    env: node
    rootDir: .
    buildCommand: |
      cd apps/frontend && pnpm install --no-frozen-lockfile && pnpm run build
      cd ../backend && pnpm install && pnpm run build
    startCommand: cd apps/backend && pnpm run start:prod
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /api/health
    autoDeploy: true

  # ფრონტენდის სერვისი
  - type: web
    name: saba-frontend
    env: node
    buildCommand: |
      npm install -g pnpm@8
      pnpm install --frozen-lockfile
      cd apps/frontend
      rm -rf .next node_modules
      pnpm install
      pnpm build
    startCommand: cd apps/frontend && pnpm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: https://saba-api-njd9.onrender.com
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
      - key: NODE_OPTIONS
        value: "--max-old-space-size=4096"
    healthCheckPath: /
    autoDeploy: true 