[build]
builder = "nixpacks"
buildCommand = "cd ../.. && pnpm install --frozen-lockfile && pnpm --filter ./apps/backend... build"

[deploy]
startCommand = "cd apps/backend && pnpm start:prod"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 10