[build]
builder = "nixpacks"
buildCommand = "cd ../.. && pnpm install --frozen-lockfile && pnpm --filter ./apps/frontend build && pnpm --filter ./apps/backend build"

[deploy]
startCommand = "pnpm start:prod"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "always"
restartPolicyMaxRetries = 10